version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: formation_node_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: formationNode
      POSTGRES_PASSWORD: formationNode
      POSTGRES_DB: formationNode
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
